name       : libcddb
version    : 1.3.2
release    : 3
source     :
    - http://internode.dl.sourceforge.net/project/libcddb/libcddb/1.3.2/libcddb-1.3.2.tar.bz2 : 35ce0ee1741ea38def304ddfe84a958901413aa829698357f0bee5bb8f0a223b
homepage   : http://libcddb.sourceforge.net/
license    : LGPL-2.1-or-later
summary    : A library for accessing a CDDB server
description: |
    Libcddb is a library that implements the different protocols (CDDBP, HTTP, SMTP) to access data on a CDDB server (e.g http://freedb.org/).
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
